#!/bin/bash

# ^c$var^ = fg color
# ^b$var^ = bg color

interval=0

# load colors
. "$DWM_PATH/black-dwm-6.3/scripts/bar_themes/nord"

cpu() {
  cpu_val=$(grep -o "^[^ ]*" /proc/loadavg)

  printf "^c$black^^b$green^ CPU"
  printf "^c$white^ ^b$grey^ $cpu_val ^d^"
}

pkg_updates() {
    updates=`pacman -Sup 2> /dev/null`
    if [ "$updates" == "" ]; then
	printf "^c$green^  Fully Updated"
    else
	count=`echo "$updates" | wc -l`
	printf "^c$green^ $count"
    fi
}

battery() {
  get_capacity="$(cat /sys/class/power_supply/BAT1/capacity)"
  printf "^c$blue^  $get_capacity"
}

brightness() {
  MAX_BRIGHTNESS=$(cat /sys/class/backlight/*/max_brightness)
  BRIGHTNESS=$(cat /sys/class/backlight/*/brightness)
  BRIGHTNESS_PERCENT=$((($BRIGHTNESS*100)/$MAX_BRIGHTNESS))

  printf "^c$red^  "
  printf "^c$red^%.0f\n" $BRIGHTNESS_PERCENT
}

mem() {
  printf "^c$blue^^b$black^ "
  printf "^c$blue^ $(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g)"
}

wlan() {
	case "$(cat /sys/class/net/wl*/operstate 2>/dev/null)" in
	up) printf "^d^ ^c$blue^^b$black^  ^d^%s" "^c$white^^b$grey^ On ^d^";;
	down) printf "^d^ ^c$blue^^b$black^ 睊 ^d^%s" "^c$white^^b$grey^ Off ^d^";;
	esac
}

today() {
    printf "^c$black^^b$darkblue^  "
    printf "^c$black^^b$blue^ $(TZ=Asia/Colombo date '+%d:%m:%Y') ^d^ "
}

clock() {
	printf "^c$black^^b$darkblue^  "
	printf "^c$black^^b$blue^ $(TZ=Asia/Colombo date '+%H:%M') ^d^"
}

vol() {
    VOL_LEVEL=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
    if [ $(pactl get-sink-mute @DEFAULT_SINK@ | cut -d " " -f 2) == "no" ]; then
	printf "^c$green^ 墳 $VOL_LEVEL ^d^"
    else
	printf "^c$green^ 婢 ^d^"
    fi
    
}


while true; do

  [ $interval = 0 ] || [ $(($interval % 3600)) = 0 ] && updates=$(pkg_updates)
  interval=$((interval + 1))

  sleep 1 && xsetroot -name "$updates $(battery) $(brightness) $(vol) $(cpu) $(mem) $(wlan) $(clock) $(today)"
done
